---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: clusterresourcequota-andrew
spec:
  selector:
    annotations:
      openshift.io/requester: andrew
  quota:
    hard:
      pods: 25
      requests:
        memory: 6Gi
        cpu: 5
      limits:
        cpu: 25
        memory: 40Gi
      configmaps: 25
      persistentvolumeclaims: 25
      services: 25



